### ISSUE TITLE
Admin API Key

### ISSUE THREAD

**Issue by AtHeartEngineer** [bandada-infra/bandada#245]
An Admin API key that allows you to create and delete groups, and fetch the API key for a group that that admin API key controls.

**Comment by AtHeartEngineer** [comment]
Nice, still looking forward to this, thanks @vplasencia

**Comment by vplasencia** [comment]
Hey @AtHeartEngineer 

@0xjei is working on it right now. It should be ready very very soon. Here is the issue: https://github.com/bandada-infra/bandada/issues/318

**Comment by AtHeartEngineer** [comment]
> Hey @AtHeartEngineer 
> 
> @0xjei is working on it right now. It should be ready very very soon. Here is the issue: https://github.com/bandada-infra/bandada/issues/318

You all are the best!
