### ISSUE TITLE
Add a tooltip to the fingerprint duration parameter in Dashboard

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#304]
Add a tooltip to the fingerprint duration input in the Dashboard explaining what fingerprint duration is.

**Comment by vplasencia** [comment]
Hey @tanyas-codes! Thanks, yes sure. 

The idea is to add a tooltip next to the `Fingerprint duration` tag when creating an off-chain group. The text will be:

```
The fingerprint is a value that represents a group. Right now the fingerprint is the Merkle Root of an Incremental Merkle Tree. Every time the group changes, the fingerprint changes too. 

The fingerprint duration indicates how long old fingerprints will be valid to verify proofs successfully.

More information about it: https://github.com/semaphore-protocol/semaphore/issues/98
```

**Comment by tanyas-codes** [comment]
yes ! do assign me this issue .

I will start working on this ,also if the text seems lengthier then i will briefly shorten it (summarize)  and ask you if it's okay to proceed .

**Comment by aguzmant103** [comment]
Hey @tanyas-codes also following up on this one :) 
Were you able to work on it? Any troubles or work pending?

**Comment by tanyas-codes** [comment]
@aguzmant103 Yes ,I had exams all this while so could'nt find the time ,I'll start with this issue this week !

**Comment by aguzmant103** [comment]
Amazing no worries :) @tanyas-codes  thanks for letting us know! Looking forward to your contributions 🙌

**Comment by tanyas-codes** [comment]
@vplasencia Hello ! I've made some draft design using the color pallete of bandada,I've attached the screenshots below,do let me know the modifications.
1)If the text length is apt?
2)the width of the tooltip 


https://github.com/bandada-infra/bandada/assets/107319582/2a02f8fb-9756-4463-9d3d-0a70e4ffffdd

changed the width 
<img width="1440" alt="verticalwidth" src="https://github.com/bandada-infra/bandada/assets/107319582/9f4868a8-e63c-452b-8047-85fa2a59777d">

**Comment by tanyas-codes** [comment]
hello!Thankyou so much ! @vplasencia ,Since you liked both of them for now I made a PR with design 1.
And made the changes you said above .
