### ISSUE TITLE
Create, update and remove one or more `Group` using an Api Key

### ISSUE THREAD

**Issue by aguzmant103** [bandada-infra/bandada#318]
Any admin with a session should be able to use a valid API Key to create, delete or update one or more off-chain groups.

Other related issues
- #225
- #245

See #446

**Comment by aguzmant103** [comment]
Pending: we need to figure out who will be the admin as they'll need to connect their wallet. 


Maybe we could do it with an API key?

**Comment by 0xjei** [comment]
Current scope: off-chain manual & credential groups
