### ISSUE TITLE
Discuss Credential groups

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#342]
Right now you can join different credential groups using the same credential, for example using GitHub you can join a group for people that have more than 2 followers and another group for people that have more than 3 followers. But if you join one of these groups, and then you are removed from that group, you can't join that group again, is this behavior fine, or it is better to remove people from these groups and then let them prove that they meet the criteria and join again? Or is it better to prevent group admins from removing people from the groups?

Other issues related to credential groups: 

- #343 

- #323

**Comment by 0xjei** [comment]
> Right now you can join different credential groups using the same credential, for example using GitHub you can join a group for people that have more than 2 followers and another group for people that have more than 3 followers. But if you join one of these groups, and then you are removed from that group, you can't join that group again.

Thank you for the explanation! Very well stated :blush: 

> is this behavior fine, or it is better to remove people from these groups and then let them prove that they meet the criteria and join again?

The nature of the use case strongly influences the approach. It is best to limit the scope to necessary interactions and delegate choices to the end-users / admin. We can consider to add a flag during the group creation phase to allow or disallow rejoining after removal.

> Or is it better to prevent group admins from removing people from the groups?

My previous proposal included a flagging system for groups.  These settings should be visible to participants to ensure they are aware of the group's rules before joining. This will prevent users from being arbitrarily removed and unable to re-enter.

> Other issues related to credential groups:
> 
> * [I can't remove a credential group if it previously had at least one member #343](https://github.com/privacy-scaling-explorations/bandada/issues/343)

This is incorrect. The admin should be able to delete the group only when there are no members. Need to be fixed.

> * [List all the credential groups #323](https://github.com/privacy-scaling-explorations/bandada/issues/323)

Agree, this is very cool. We can think to provide a sort of search engine with a bar, filters, and ordering!

**Comment by aguzmant103** [comment]
Thank you @vplasencia for summarizing the problem very well
Agree with @0xjei i think the flag during group-creation would be the best path forward

Client apps then should alert users they're joining a "they can kick me out" group

-----

Last question: is this architecture / feature possible when we go onchain?
I would imagine yes, it should be a simple boolean field that controls what admins can or can't do

**Comment by 0xjei** [comment]
> Thank you @vplasencia for summarizing the problem very well Agree with @0xjei i think the flag during group-creation would be the best path forward
> 
> Client apps then should alert users they're joining a "they can kick me out" group
> 
> Last question: is this architecture / feature possible when we go onchain? I would imagine yes, it should be a simple boolean field that controls what admins can or can't do

Thank you @aguzmant103 for going through everything so well!

Yes, absolutely! You are right! They can be one or more boolean values or whatever data structure best optimises the gas consumption on-chain.

**Comment by 0xjei** [comment]
@aguzmant103 @vplasencia should we move this to Github discussions?

**Comment by aguzmant103** [comment]
Agree it's best suited there @0xjei 

Idk though if we need to discuss it further or if it's a "decision taken" and we need to create new issues based on this decision

**Comment by 0xjei** [comment]
> Agree it's best suited there @0xjei
> 
> Idk though if we need to discuss it further or if it's a "decision taken" and we need to create new issues based on this decision

Agreed, feel free to post your feedback here (and @vplasencia too) to get a consensus on the relevant issues. My views:
- [ ] define settings / rules per group at creation time (e.g. "The admin can delete the group if there are no members", "The admin can decide to arbitrarily remove you from the group", etc.)
- [ ] create a search engine for groups on the home page of the dashboard (filters, labels, other features)

**Comment by aguzmant103** [comment]
Agree @0xjei

**Comment by 0xjei** [comment]
> Agree @0xjei

Brilliant, I proceed to create the issues and consider this closed.
