### ISSUE TITLE
Upgrade to Ethers.js v6

### ISSUE THREAD

**Issue by aguzmant103** [bandada-infra/bandada#366]
FYI @vplasencia

**Comment by neel-ds** [comment]
Can I pick this issue and upgrade it to ethers@^6.10 with necessary changes?

**Comment by vplasencia** [comment]
Hey @neel-ds! Yes, sure. Do you want me to assign you this issue?

**Comment by neel-ds** [comment]
Hey @vplasencia 
Yes! I would like to contribute. Please assign it to me, and I will ensure that my contributions align with the project's contribution guidelines.

**Comment by vplasencia** [comment]
Hey @neel-ds. Done ✅

Thank you so much. Let us know if you have questions or need any help.

**Comment by neel-ds** [comment]
> Hey @neel-ds. Done ✅
> 
> Thank you so much. Let us know if you have questions or need any help.

Hello! I have upgraded the package and changed methods or imports accordingly. But I am stuck with some response type issues in Bandada Interface file from contracts. I will try to solve it ASAP. If there is anything I will send request on Discord.

**Comment by vplasencia** [comment]
Hey @neel-ds 

Great. Thank you for the update. Feel free to always ask questions.

**Comment by 0xjei** [comment]
Hello @neel-ds. How's going with the upgrade? I'm going to work on #355 and I'll potentially need the Ethers V6. Let me know if you need help!

**Comment by neel-ds** [comment]
> Hello @neel-ds. How's going with the upgrade? I'm going to work on #355 and I'll potentially need the Ethers V6. Let me know if you need help!

I am stuck with errors in contracts. I solved the typechain-types issue by changing hardhat config. I tried upgrading `@nomiclabs/hardhat-ethers` and `@typechain/ethers-v6` to latest but build fails. As ethers v6 doesn't support utils package
![Screenshot 2024-02-11 at 4 36 00 PM](https://github.com/privacy-scaling-explorations/bandada/assets/79443588/ec1eb673-9bd4-452b-ba8a-30d6cddf0870)

**Comment by 0xjei** [comment]
Hello @neel-ds, any news on this PR? Do you need any further help? Please, let us know! :)

**Comment by neel-ds** [comment]
Thanks for reaching out @0xjei, I will try to finish it asap. Connect back to you on discord.

**Comment by neel-ds** [comment]
Hello @0xjei, 
I have upgraded the ethers package to v6. I did the needful but can't resolve build issue. I would appreciate your help here to review the work and provide any feedback to resolve issue. Pushed the commits in my [branch](https://github.com/neel-ds/bandada/tree/refactor/ethers-v6). Please check out dm on Discord for more details.

**Comment by 0xjei** [comment]
> Hello @0xjei, 
> 
> I have upgraded the ethers package to v6. I did the needful but can't resolve build issue. I would appreciate your help here to review the work and provide any feedback to resolve issue. Pushed the commits in my [branch](https://github.com/neel-ds/bandada/tree/refactor/ethers-v6). Please check out dm on Discord for more details.

Thank you! I will have a look now.
