### ISSUE TITLE
Dashboard: List on-chain groups starting from the most recently created

### ISSUE THREAD

**Issue by aguzmant103** [bandada-infra/bandada#433]
More context:
https://github.com/privacy-scaling-explorations/bandada/issues/344

**Comment by waddaboo** [comment]
Hi, I would like to take on this issue :)

**Comment by vplasencia** [comment]
Hey @waddaboo great, thanks. What is the error you are getting?

**Comment by waddaboo** [comment]
I have been trying to sign in to my local bandada with Coinbase Wallet but it didn't prompt the QR code for most of the time, and even for the times that it did, it always ends with unable to verify signature.

**Comment by vplasencia** [comment]
Hey @waddaboo 

It looks like connecting with Coinbase Wallet is not working properly. Sorry about that. Here is the issue: https://github.com/bandada-infra/bandada/issues/487

Can you try with Metamask?

**Comment by waddaboo** [comment]
> It looks like connecting with Coinbase Wallet is not working properly. Sorry about that. Here is the issue: https://github.com/bandada-infra/bandada/issues/487

Managed to login in [bandada.pse.dev](bandada.pse.dev), but only on mobile. Thought it was error on my machine haha.

> Can you try with Metamask?

Tried Metamask but nothing popup after clicking as well.

**Comment by waddaboo** [comment]
Hey @vplasencia, I found out in order for on-chain groups to sort by most recent created, some changes must be made at `@semaphore-protocol/data`, specifically [here](https://github.com/semaphore-protocol/semaphore/blob/main/packages/data/src/subgraph.ts) at `getGroups` so that it can return the timestamp for sorting use.

```JavaScript
const config: AxiosRequestConfig = {
    method: "post",
    data: JSON.stringify({
        query: `{
            groups ${filtersQuery} {
                id
                merkleTree {
                    root
                    depth
                    size
                }
                admin
                ${
                    members === true
                        ? `members(orderBy: index) {
                    identityCommitment
                }`
                        : ""
                }
                ${
                    validatedProofs === true
                        ? `validatedProofs(orderBy: timestamp) {
                    message
                    merkleTreeRoot
                    merkleTreeDepth
                    scope
                    nullifier
                    points
                    timestamp
                }`
                        : ""
                }
            }
        }`
    })
}
```

Any suggestion on how should this proceed?

**Comment by vplasencia** [comment]
Hey @waddaboo! There are some ways to solve this without modifying the Semaphore package. Here are two options:

1- Recreate the same that function is doing under the hood. This way you have full control of the code and can modify what you want. 

2- Run `yarn patch @semaphore-protocol/data` and then go to the files specified in the console log and modify the files, then run what appears in the console log to save the changes. 

The change would be adding:
```
orderBy:timestamp, orderDirection:desc
```

After running the second command to save the changes, you should see a new file inside the `.yarn/patches` folder with `@semaphore-protocol/data` as part of the name. That file would have the changes.

Let us know if you have more questions.

**Comment by waddaboo** [comment]
Hey @vplasencia thanks for the detailed step-by-step guide!
