### ISSUE TITLE
List all the groups per AdminID

### ISSUE THREAD

**Issue by aguzmant103** [bandada-infra/bandada#493]
**Is your feature request related to a problem? Please describe.**
This was requested/asked in ETHDam 2024 Hackathon. Seems like a good devex need

**Describe the solution you'd like**
I would like to have an API SDK method that returns all the groups of an AdminID.

**Describe alternatives you've considered**
Another related but different needs could be:
-  Return all groups per memberID

**Additional context**

There is an API endpoint to get all the groups using an adminId: https://api.bandada.pse.dev/#/groups/GroupsController_getGroups

If devs use the API SDK, they will need to get all groups using the [`getGroups()`](https://docs.bandada.pse.dev/api-sdk#get-groups) function and then filter by AdminId.

**Comment by waddaboo** [comment]
Hi! I would like to work on this issue.

Would you like it to be implemented into `getGroups(adminId)` with optional `adminId` or separate it to `getGroupsByAdminId(adminId)`?

Similar question for `memberId`, would you like it to be implemented as an optional query to `getGroups` in `groups.service.ts` or separate it?

**Comment by 0xjei** [comment]
> Hi! I would like to work on this issue.
> 
> Would you like it to be implemented into `getGroups(adminId)` with optional `adminId` or separate it to `getGroupsByAdminId(adminId)`?
> 
> Similar question for `memberId`, would you like it to be implemented as an optional query to `getGroups` in `groups.service.ts` or separate it?

hello @waddaboo thanks for the interest.

tbh i'm okay with specific functions - `getGroups()` & `getGroupsByAdminId()` - or applying filters per field to the generic version - getGroups(filterBy: <field>)

**Comment by vplasencia** [comment]
Hey @waddaboo do you want me to assign you this issue?

> Hi! I would like to work on this issue.
> 
> Would you like it to be implemented into `getGroups(adminId)` with optional `adminId` or separate it to `getGroupsByAdminId(adminId)`?

Having separated functions in the API SDK is fine. It would be: `getGroupsByAdminId()` and `getGroupsByMemberId()`.

> Similar question for `memberId`, would you like it to be implemented as an optional query to `getGroups` in `groups.service.ts` or separate it?

Yes, an optional query in the backend is fine: 

https://github.com/bandada-infra/bandada/blob/79cd218d5d28d47de083a9737925f69881f2e178/apps/api/src/app/groups/groups.service.ts#L814

**Comment by waddaboo** [comment]
> Hey @waddaboo do you want me to assign you this issue?

Hey @vplasencia! Yes, please :)

> Having separated functions in the API SDK is fine. It would be: `getGroupsByAdminId()` and `getGroupsByMemberId()`.
Yes, an optional query in the backend is fine:

Noted, I will proceed with the suggested solution.

**Comment by vplasencia** [comment]
Hey @waddaboo 

I just assigned you this issue. Please, let us know if you have any questions.
