### ISSUE TITLE
Add the docs link to the header in the dashboard app

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#497]
## Description

As part of ETHDam feedback, it would be nice to have the docs link in the Bandada dashboard.

The idea is to add the docs link to the header. The link can be called `Documentation`

Docs link: https://docs.bandada.pse.dev

## Reference

Semaphore docs header: https://semaphore.pse.dev

## Context

Feedback from [`Azure`](https://github.com/ahmedhamedaly) when building [`0x2FA`](https://github.com/0x2fa-org/0x2fa).

**Comment by SandipGyawali** [comment]
![image](https://github.com/bandada-infra/bandada/assets/66510112/db1b7043-cfc8-4540-90ed-a79c30bf620f)

hey @vplasencia i can work on this issue can you assign me ?

**Comment by SandipGyawali** [comment]
@vplasencia sure thankyou.

**Comment by SandipGyawali** [comment]
![image](https://github.com/bandada-infra/bandada/assets/66510112/b89fe629-57b8-48a6-9e7f-92137c960f6e)


@vplasencia i am having issue while connecting can you suggest me any thing to resolve this issue ?

**Comment by vplasencia** [comment]
Hey @SandipGyawali! Is that locally? Can you refresh the page and try again?

**Comment by SandipGyawali** [comment]
@vplasencia i tried multiple time with different wallets didn't work.

by the way i used the docker for my setup, i will try again after some time

**Comment by vplasencia** [comment]
Ahhh got it. Try to run it without docker. Just clone the repo, then install the dependencies (`yarn`), then run `yarn build`, then run `yarn dev`.

**Comment by SandipGyawali** [comment]
> Ahhh got it. Try to run it without docker. Just clone the repo, then install the dependencies (`yarn`), then run `yarn build`, then run `yarn dev`.

ok, i wil

**Comment by SandipGyawali** [comment]
@vplasencia can you review the pull requirest please ?

**Comment by vplasencia** [comment]
Hey @SandipGyawali I will review the Pull Request as soon as possible. Thank you very much for creating it.
