### ISSUE TITLE
API SDK types are not working

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#498]
## Description

This is part of the ETHDam feedback. The API SDK types were not found.

## Screenshot

<img width="930" alt="Screenshot_2024-04-23_at_08 27 32" src="https://github.com/bandada-infra/bandada/assets/52170174/adee38d1-6295-48ab-80c0-58d13b0dd776">

## Project link

https://github.com/0x2fa-org/0x2fa

## Context

Feedback from [`Azure`](https://github.com/ahmedhamedaly) when building [`0x2FA`](https://github.com/0x2fa-org/0x2fa).

**Comment by waddaboo** [comment]
Hi @vplasencia, I tried to work on this issue but I'm not able to replicate this error. Is this bug fixed?

**Comment by vplasencia** [comment]
Hey @waddaboo! The issue shouldn't be fixed yet. 

I think the way to replicate this issue would be cloning this repo: https://github.com/0x2fa-org/0x2fa and removing this line `// @ts-ignore` (https://github.com/0x2fa-org/0x2fa/blob/main/app/src/app/page.tsx#L11), then you should see the error. 

I haven't seen this error in other projects before.

Let us know if you have more questions.

**Comment by waddaboo** [comment]
As a temporary solution, changing the `moduleResolution` from `bundler` to `Node` in `tsconfig.js` will solve the problem. Will look into updating the `package.json` and/or `tsconfig.json` for a better fix.
