### ISSUE TITLE
Make it easier to join Credential groups

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#513]
## Description

Right now, joining a credential group involves creating a URL. It would be nice to make it easier for devs to create this URL. 

## Possible ideas

One idea could be to create a function in the API SDK to join a Credential group and devs would add the values as parameters and the function will generate the URL for them. 

Feel free to post other ideas.

**Comment by waddaboo** [comment]
Hello @vplasencia, I would like to take on this issue!

So the idea was to create an API SDK that takes in `clientUrl` and `groupId` and returns a new URL with invite code?

**Comment by vplasencia** [comment]
Hey @waddaboo! Thanks. Would you like me to assign you think issue?

The idea is to make it easier for devs to work with credential groups. Right now, when you want to work with credential groups, you need to generate an url like this (https://github.com/bandada-infra/boilerplate/blob/main/pages/groups.tsx#L128). The idea is to have a function in the API SDK to make it easier to generate that URL and improve the developer experience when working with credential groups.

Here is another example of URL when working with credential groups: https://github.com/bandada-infra/bandada/blob/main/apps/client/src/pages/home.tsx#L132-L136

Please, let me know if you have more questions or ideas.

**Comment by waddaboo** [comment]
> Hey @waddaboo! Thanks. Would you like me to assign you think issue?

Yes, please :)

Right, I imagine it would be something like this:

```ts
function joinCredentialGroups(baseUrl: string, groupId: string, commitment: string) {
  // group validation
  const group = await getGroup(groupId)
  const providerName = group.credentials.id ...
  ...

  const url = `${baseUrl}/credentials?group=${groupId}&member=${commitment}&provider=${providerName}`

  return url
}
```

**Comment by vplasencia** [comment]
Please @waddaboo let us know if you need any help. Thanks.

**Comment by waddaboo** [comment]
> I just assigned you the issue. Yes, correct. Also including the redirect uri.

Noted and thanks! :)
