### ISSUE TITLE
Remove Goerli groups section

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#518]
## Description

In this PR https://github.com/bandada-infra/bandada/pull/431 Sepolia was added as the default network but this PR also added a section to display the Goerli groups. 

The idea is to remove the section of the Goerli groups.

**Comment by Dozie2001** [comment]
Hello Would love to be assigned to this if it's still open

**Comment by vplasencia** [comment]
Hey @Dozie2001! Yes, it's still open. I just assigned you the issue. Please, let us know if you have any questions.

**Comment by Dozie2001** [comment]
Hello @vplasencia  should I also replace them with Sepolia alternatives

**Comment by vplasencia** [comment]
Hey @Dozie2001 

> should I also replace them with Sepolia alternatives

No, it's not necessary to replace it.

The idea is to remove that Goerli group section because it was temporal.

For more context, this PR added the Goerli groups as a temporal solution: https://github.com/bandada-infra/bandada/pull/431 and the Goerli group component was added here: https://github.com/bandada-infra/bandada/pull/431/files#diff-d0810a7ba08fe87d859ee593a17e9addb02181e5297e30b42be188fbb45777c7

The idea is to remove the Goerli group component and also remove where it's called.

Let us know if you have more questions.
