### ISSUE TITLE
Add Pairwise to your list of awesome projects using your tech

### ISSUE THREAD

**Issue by GriffGreen** [bandada-infra/bandada#531]
https://pairwise.vote

not sure what you all want to add us to your website, but tell me and I will put it in the issue

**Comment by vplasencia** [comment]
Hey @GriffGreen 

It looks great! Feel free to add your project information to a new issue. 

This structure can help: https://github.com/bandada-infra/bandada/blob/main/apps/website/shared/data/projects.ts#L14

**Comment by aguzmant103** [comment]
Hey @GriffGreen looks awesome! 🤩  so happy to see this built

i) can you make a PR to add it? (that way you also get a Bandada GitPOAP for contributing lol)

ii) would love to chat further with you about plans with it :) are you in PSE Discord? Would love to catch up

**Comment by aguzmant103** [comment]
Added :) https://github.com/bandada-infra/bandada/commit/aa1d72e94e2dfbc8a0316085c76047a977e308cf

Thanks @GriffGreen !

**Comment by aguzmant103** [comment]
@gitpoap-bot @GriffGreen
