### ISSUE TITLE
Support Polygon Amoy because Polygon Mumbai is deprecated

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#534]
## Description

Polygon Mumbai is deprecated, then Bandada should be updated to use Polygon Amoy instead.

## Tasks

- [x] Update the code
- [x] Update the Bandada environment variable in the server

**Comment by Agrim-Sharma174** [comment]
hey @vplasencia, I would like to work on this, please assign.

**Comment by vplasencia** [comment]
Hey @Agrim-Sharma174, done. Thank you. Please let us know if you have questions.

**Comment by ajayadsul** [comment]
Is this issue is available for proceeding further

**Comment by vplasencia** [comment]
Hey @ajayadsul! Do you want me to assign the issue to you?

**Comment by vplasencia** [comment]
Hey @ajayadsul! Are you the owner of these two accounts: @ajayadsul and @AjayAdsule ?

**Comment by AjayAdsule** [comment]
@vplasencia  Yes ,i just mixed up my personal and work account apologize for that

**Comment by vplasencia** [comment]
Got it. No worries. Feel free to start working on this issue and ask us any questions you may have. 

Which account are you going to use to assign the issue to?

**Comment by AjayAdsule** [comment]
please assign to @AjayAdsule

**Comment by AjayAdsule** [comment]
![image](https://github.com/user-attachments/assets/5e540786-2929-48b8-b88c-d210d577d3d9)

![image](https://github.com/user-attachments/assets/f9d5cc52-b042-4779-8e8f-1fb1f9be9625)

@vplasencia   require any changes ?

**Comment by vplasencia** [comment]
It looks great! 

I think that if you filter the word `mumbai` in the Bandada project you will find all the places that should be updated.

**Comment by AjayAdsule** [comment]
@vplasencia  i am creating pr

**Comment by vplasencia** [comment]
Hey @AjayAdsule I just merged the PR. The server was also updated with the new environment variable. Thank you very much.

**Comment by vplasencia** [comment]
Hey @Agrim-Sharma174! This issue is completed. If you're still interested in contributing, please feel free to ask for any open good first issue here: https://github.com/bandada-infra/bandada/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

I plan to add more good first issues soon. Thank you!

**Comment by AjayAdsule** [comment]
@vplasencia  thanks looking forward for more contribution on banada community
