### ISSUE TITLE
Add more tests to increase test coverage

### ISSUE THREAD

**Issue by waddaboo** [bandada-infra/bandada#535]
**Is your feature request related to a problem? Please describe.**
Based on the current run of `yarn test:coverage`, the total coverage for all the tests are as below:
|File | Statements|
|----|-------------|
| apps/api/src/app/auth | 100% |
| apps/api/src/app/credentials | 93.57% |
| apps/api/src/app/groups | 94.51% |
| apps/api/src/app/invites | 100% |
| apps/api/src/app/utils | 100% |
| libs/api-sdk/src | 100% |
| libs/credentials/src | 94.8% |
| libs/utils/src | 83.33% |

**Describe the solution you'd like**
I would like to add more tests to improve the test coverage.

**Comment by od-hunter** [comment]
hello @vplasencia @waddaboo i would like to on this ?

**Comment by vplasencia** [comment]
Hello @od-hunter 👋

@waddaboo is working on it. I will create other similar issues soon. Feel free to always ask for any other issues. Thank you very much 🙏

**Comment by od-hunter** [comment]
@vplasencia ok, Will be looking forward to solving other issues, thank you.🙏🏾
