### ISSUE TITLE
Incorrect links in discussion thread: Projects built using Bandada

### ISSUE THREAD

**Issue by waddaboo** [bandada-infra/bandada#539]
**Describe the bug**
The hyperlinks of `BrickWall` and `B-Hook` has been swapped in the Projects built using Bandada discussion thread.

Similar error here: https://github.com/bandada-infra/bandada/blob/ed20897f16999a1de888aeb7be882cdabbf63d77/apps/website/shared/data/projects.ts#L46-L66

**To Reproduce**
Clicking on `BrickWall` brings users to the `B-Hook` website; and clicking on `B-Hook` brings users to the `BrickWall` website.

**Expected behavior**
Clicking on the hyperlinks should bring users to the correct website.

**Comment by martinvibes** [comment]
hello @waddaboo can i be assigned to this issue?

**Comment by vplasencia** [comment]
Hey @martinvibes I just closed the issue because the PR solving this issue was merged yesterday. Thank you very much for the interest. Feel free to ask for other issues. We will create new issues soon.

**Comment by martinvibes** [comment]
@vplasencia  ok i will apply again when you create new issues
