### ISSUE TITLE
Connect Metamask is not working in the client app

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#546]
## Description

When going to the Client app (https://client.bandada.pse.dev) and clicking on the `Connect Metamask` button, it does not work.

**Comment by Dhanraj30** [comment]
Its fine and working properly
see here 


https://github.com/user-attachments/assets/7ac8f89b-78f4-498e-9a7f-57519c3cf671

**Comment by vplasencia** [comment]
Hey @Dhanraj30! It was not working for me but after I deactivated the Phantom wallet, it started to work again. Maybe I just need to update the Phantom wallet or log in to it. Thank you very much for pointing out 🙏

**Comment by vplasencia** [comment]
Thank you very much! I hope you like this @gitpoap-bot @Dhanraj30
