### ISSUE TITLE
The group card size changes when the title or description is too large

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#553]
## Description

The idea is to make the group cards responsive. Right now, when the name or description of a group is really large, the group card size changes.

## Context

This issue was reported by @family36 in the following comment: https://github.com/bandada-infra/bandada/issues/323#issuecomment-2352453262

**Comment by AjayAdsule** [comment]
@vplasencia  how can we tackle this styling issue 

[ ] : By Adding maximum length on character
[ ] : By fix the width of description element and show content by scrolling, attach video of scrolling 

![image](https://github.com/user-attachments/assets/4ed216b3-a885-47f7-a1a6-d58d3a8d0ec4)

![image](https://github.com/user-attachments/assets/5410a026-5ce7-4534-b6de-53dc6d2c3a31)

![image](https://github.com/user-attachments/assets/8ee3c685-8f1b-4918-9483-45baf5f4a2c7)


https://github.com/user-attachments/assets/d218f324-e57f-4fbf-8b8f-7a807272a5de

**Comment by vplasencia** [comment]
Hey @AjayAdsule! Would you like me to assign this issue to you?

Thank you, it looks really nice. What about truncating the text in the card, then people will know that there is more info. This is the way to use it with chakra ui: https://v2.chakra-ui.com/docs/components/text#truncate-text

It would be adding `noOfLines={3}`, I think 3 could be fine for this card, what do you think?

**Comment by AjayAdsule** [comment]
@vplasencia  Please assign

**Comment by vplasencia** [comment]
Hey @AjayAdsule I just assigned the issue to you. Let us know if you have any questions.

**Comment by AjayAdsule** [comment]
@vplasencia, I set noOfLines={3}, and it looks great. However, I have one doubt. In the snapshot from #332 (comment), there is no limit on the title of the group element. But in my dev mode, there seems to be a limit on the number of lines when entering text. Could you clarify this ? 



![Screenshot 2024-09-20 222228](https://github.com/user-attachments/assets/4de27c02-d1ca-4f1f-b49a-3a454b6b60c6)
![Screenshot 2024-09-20 222245](https://github.com/user-attachments/assets/56b850e5-10c4-4951-831d-4c6c4d031b78)

**Comment by AjayAdsule** [comment]
@vplasencia, I set noOfLines={3}, and it looks great. However, I have one doubt. In the snapshot from https://github.com/bandada-infra/bandada/issues/323 (comment), there is no limit on the title of the group element. But in my dev mode, there seems to be a limit on the number of lines when entering text. Could you clarify this ?


![image](https://github.com/user-attachments/assets/eee715ee-1d7d-4892-a93e-900ee1dd72aa)
![image](https://github.com/user-attachments/assets/b4073e99-452f-4521-b37a-e64e0c8a9aa6)
![image](https://github.com/user-attachments/assets/cf5410ac-9fd4-42a1-bb8f-35feac07fd2c)

**Comment by vplasencia** [comment]
Hey @AjayAdsule yes, for the title there is limit. 

There is no limit for the description. In the comment image, it looks like there is no title because it's hidden, it was probably done manually, but the description is a long text without spaces. It's true that if you add a long text without spaces as description, the layout breaks.

**Comment by AjayAdsule** [comment]
@vplasencia  right now i am applying maximum width for text element , there is second option are we can set max-width of card and text-wrap for text 

![image](https://github.com/user-attachments/assets/5c98852d-0139-42d2-b7e0-c8be7d8bdd29)
![image](https://github.com/user-attachments/assets/8fde0467-b877-46df-9dfb-a2de6dfb8aeb)


![image](https://github.com/user-attachments/assets/16346e5b-e71b-4b4b-94a2-e3a2c21dc879)
![image](https://github.com/user-attachments/assets/9761a1bd-7463-4f87-ac00-f8f8e9f3683a)


![image](https://github.com/user-attachments/assets/36faa387-43c1-44c0-88fd-781a4edce8e3)
![image](https://github.com/user-attachments/assets/18312205-7a9c-47e4-b3eb-b2bbc8723ac0)

**Comment by vplasencia** [comment]
Hey @AjayAdsule I think the second option sounds great! The idea is to make sure that all the cards have always the same size no matter the title or description length.

Can the credential group card in the last image have the same size as the on-chain group card? It would be nice to keep consistency.

**Comment by AjayAdsule** [comment]
@vplasencia  for group view i added maxW to 70vw and for my groups i added maxW to 370px because it has already min-w set to 330px
please tell me for any change i will do it otherwise i will make PR

![image](https://github.com/user-attachments/assets/956d661c-1d35-472e-85cc-f46e389961cd)

![image](https://github.com/user-attachments/assets/c76b5df0-c9a2-4fc9-92ac-11d5547fc4e3)

![image](https://github.com/user-attachments/assets/c10855b7-9979-4a8b-b784-c3b444d541da)

**Comment by vplasencia** [comment]
Hey @AjayAdsule great. What about adding `noOfLines={2}` instead of `noOfLines={3}` so that the word members and the number above are at the same level for all the cards, no matter the size of the title or description? You can see the difference in the off-chain and on-chain group cards.

**Comment by AjayAdsule** [comment]
@vplasencia It's done. I have one question regarding the group view page should we truncate the text or display the full description of the groups? Currently, I've set noOfLine={5}

![image](https://github.com/user-attachments/assets/eaa4ff9f-b808-49fc-8125-042bcb792813)


![image](https://github.com/user-attachments/assets/11e30636-c672-4671-82c0-ea25c415b0aa)
![image](https://github.com/user-attachments/assets/b82e6078-7f14-4477-9ac0-6f16ebfd3fe6)

**Comment by vplasencia** [comment]
Hey @AjayAdsule looks great! Thanks.

Regarding the group page, it's better to show the entire description so that people can read everything.
