### ISSUE TITLE
Groups page is not responsive

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#557]
## Description

It would be nice to make the page where the group cards are displayed responsive. 

<img width="430" alt="Screenshot 2024-09-22 at 11 53 32 AM" src="https://github.com/user-attachments/assets/b3f2230a-1c35-45c3-a560-64c0a942d60b">

**Comment by Benjtalkshow** [comment]
@vplasencia ,
Can i be assigned to this? i am ready to work on it. Thanks

**Comment by vplasencia** [comment]
Hey @Benjtalkshow done! Thanks.

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow done! Thanks.

Thanks. 
How can i contact you? Any telegram group or handle?

**Comment by vplasencia** [comment]
Hey @Benjtalkshow feel free to ask questions here.

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow feel free to ask questions here.

Will there be any reward for completing the tasks?

**Comment by vplasencia** [comment]
Hey @Benjtalkshow 

> Will there be any reward for completing the tasks?

For the first time Bandada contributors, there is always a [GitPOAP](https://www.gitpoap.io/gp/1089).

If you mean money, no.

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow
> 
> > Will there be any reward for completing the tasks?
> 
> For the first time Bandada contributors, there is always a [GitPOAP](https://www.gitpoap.io/gp/1089).
> 
> If you mean money, no.

alright

**Comment by vplasencia** [comment]
Hey @Benjtalkshow do you still want to work on these issues? Whatever you decide will be fine.

**Comment by Benjtalkshow** [comment]
yea, will work on it

**Comment by vplasencia** [comment]
Hey @Benjtalkshow! Got it. You've asked to work on many issues, what about selecting the one you prefer and work on it and then ask for another so that you can focus on one and other people can work on others too?

**Comment by Benjtalkshow** [comment]
i can fix them

**Comment by Benjtalkshow** [comment]
@vplasencia ,
I have successfully connected the wallet. I will begin working ASAP

**Comment by yagopajarino** [comment]
Hi @vplasencia! Could I get assigned to this one?

I'm thinking about changing the display mode from grid to flex column for small/medium screens on both all groups, my groups and the search bar sections

I'll be asking for the assignment on #558 as well

**Comment by vplasencia** [comment]
Hey @yagopajarino! Sounds great. I just assigned this issue. Feel free to ask any questions you may have.
