### ISSUE TITLE
Refactor `api-sdk` tests to make them more atomic

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#583]
## Description

The idea is to remove the `let apiSdk: ApiSdk` variable from [here](https://github.com/bandada-infra/bandada/blob/main/libs/api-sdk/src/index.test.ts#L26) to make the api-sdk tests more atomic. Then the assignments should be all constants: `const apiSdk = new ApiSdk(...` instead of `apiSdk = new ApiSdk(...`.

**Comment by jaykayudo** [comment]
Can I jump on this task?

**Comment by vplasencia** [comment]
Hey @jaykayudo! Yes. Do you want me to assign this issue to you?

**Comment by jaykayudo** [comment]
> Hey @jaykayudo! Yes. Do you want me to assign this issue to you?

@vplasencia Yes. I will like that.

**Comment by vplasencia** [comment]
Hey @jaykayudo! Done. Feel free to ask any questions you may have.

**Comment by jaykayudo** [comment]
@vplasencia  PR made.
