### ISSUE TITLE
Dashboard: Create a section to show the Admin ID of the group in the group page

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#588]
## Description

The idea is to create a section with a copy button like the Group ID section but displaying the Admin ID so that it is easier for the users to copy the Admin ID. 

## Context

File to update: https://github.com/bandada-infra/bandada/blob/main/apps/dashboard/src/pages/group.tsx

Group page: https://app.bandada.pse.dev/groups/off-chain/53987951090514654300098040886025

This issue was created as part of the feedback at ETHRome 2024.

**Comment by pheobeayo** [comment]
Could I try solving this?

**Comment by vplasencia** [comment]
Hey @pheobeayo! Yes. Would you like me to assign this issue to you?

**Comment by pheobeayo** [comment]
Yes I would love that @vplasencia

**Comment by vplasencia** [comment]
Hey @pheobeayo! Done. Feel free to ask any questions you may have.

**Comment by pheobeayo** [comment]
Okay, thank you, I will get right on it

**Comment by pheobeayo** [comment]
@vplasencia I have implemented the changes but I couldn't commit my changes on the branch I created
I kept having this error
![image](https://github.com/user-attachments/assets/ce0c4198-2d7f-4a51-869d-198b69e1e56e)
Can you show me how to make the commit successfully

**Comment by vplasencia** [comment]
Hey @pheobeayo! Great! Please run `yarn commit` to write the commit messages.
