### ISSUE TITLE
Create a tutorials section to add how to work with groups

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#603]
## Description

The idea is to make it easier for devs to use the Bandada groups.

There will be a new section in the Bandada docs called `Tutorials` to explain step by step with screenshots and code how to create and use (add a member):

- An off-chain group
- On-chain group
- Credential off-chain group

**Comment by Akhil-2310** [comment]
Hi @vplasencia can you assign this issue to me? Thanks

**Comment by vplasencia** [comment]
Hey @Akhil-2310! Thank you very much for the interest. This issue was solved recently. I will close this PR as completed but feel free to create an issue to propose any other tutorial you would like to work on or pick any other open issue.
