### ISSUE TITLE
Creating onchain group without waiting for input

### ISSUE THREAD

**Issue by aguzmant103** [bandada-infra/bandada#609]
**Describe the bug**
When I want to create an onchain group, it goes to the next step without waiting for input like name, fingerprint duration, etc.

**To Reproduce**

1. Go to Dashboard
2. Click on 'Add group..'
3. Click on 'Onchain'
4. See that the step moves forward without waiting for me to click "Continue" or add the group information (like Name or figerprint duration)

**Expected behavior**
To wait for me until I click continue.

**Screenshots**
<img width="980" alt="image" src="https://github.com/user-attachments/assets/ae61dd87-b8cd-4f57-af07-1e2a9ea99ef9">
<img width="980" alt="image" src="https://github.com/user-attachments/assets/d3d769a5-4e2c-4b02-9a60-52a0960ca36e">

**Technologies (please complete the following information):**

-   Node.js version
-   NPM version
-   Solidity version

**Additional context**

**Comment by waddaboo** [comment]
@aguzmant103 @vplasencia Hey! I will work on this issue.

Since the group name and description is not being used when creating an on-chain group, I'm considering to disable/hide the text box from UI and the hide the [untitled] at group preview. What do you guys think?

**Comment by vplasencia** [comment]
Hey @waddaboo! I agree, I think it's better to hide the text box from the UI and [untitled].

**Comment by aguzmant103** [comment]
Hey agreed @waddaboo disable makes more sense.

Just additionally, as a user I want to be able to click "On chain" and not move to the next screen until I click "continue"

The rest makes sense in your explanation :)
