### ISSUE TITLE
Add dynamic redirect to Dashboard Bandada logo

### ISSUE THREAD

**Issue by waddaboo** [bandada-infra/bandada#650]
## Description

The Bandada logo in the Dashboard navigation bar is currently hardcoded to redirect to https://app.bandada.pse.dev. 

It would be great to add a dynamic redirect based on the current environment.

### Example:
if local, redirect to http://localhost:3001/
if staging, redirect to https://app-staging.bandada.pse.dev/
if production, redirect to https://app.bandada.pse.dev/

![image](https://github.com/user-attachments/assets/e6c86a69-bbb7-478f-913b-de8b11aa3dc1)

**Comment by spudoodle** [comment]
Hey, I would like to work on this

**Comment by vplasencia** [comment]
Hey @spudoodle! Sounds great. Would you like me to assign you this issue?

**Comment by spudoodle** [comment]
Sure

**Comment by vplasencia** [comment]
Hey @spudoodle! You have the issue assigned now. Feel free to ask any questions you may have.

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies. My expertise includes: Figma Nuxt.js,  React js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project.
My approach towards this issue would be first to locate the navbar.tsx file in the component folder then i would create a function that uses usenaviagate hook to redirect based on the environment by using the REACT_APP_REDIRECT_URL located in the env file.  ETA is 12hrs

**Comment by ONEONUORA** [comment]
Is it okay if I tackle this?.  I am a full stack  and blockchain developer

**Comment by aidenwong812** [comment]
I’d love to work on this task.

**Comment by pheobeayo** [comment]
I'd love to give this a go.

**Comment by vplasencia** [comment]
Hey @Shalomnze @ONEONUORA @aidenwong812 @pheobeayo 

Thank you for the interest. This issue was already assigned and solved here: https://github.com/bandada-infra/bandada/pull/651

Feel free to ask for any other open issue.

**Comment by davedumto** [comment]
Hi,
My name is David, and I am a frontend developer skilled in JavaScript, TypeScript, React.js, and Next.js. I will update the Bandada logo in the dashboard navigation bar to dynamically redirect based on the current environment (local, staging, production).
I’ll implement and test the logic to ensure seamless functionality across environments. ETA: 1 day

**Comment by aidenwong812** [comment]
@vplasencia Are there any issues that I can attempt?
